global_frame: odom
rolling_window: true

update_frequency: 30.0
publish_frequency: 30.0
plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}

